name: CI/CD Pipeline with Codespaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install flake8
          pip install -r requirements.txt

      - name: Run Linter
        run: flake8 . || true

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        working-directory: ./
        run: python -m unittest discover -s src/test/unit_test -p "*.py"

  deploy-to-runner:
    name: Deploy and Test Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t mlops-app:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name mlops-app mlops-app:latest
          echo "Docker container is running on port 8000."

      - name: Wait for Service to Start
        run: sleep 10

      - name: Test Deployment with cURL
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" \
            -d '{"features": [13.2, 2.77, 2.51, 24.5, 86.0, 1.45, 1.25, 0.5, 1.7, 6.5, 1.05, 3.33, 820.0]}' \
            http://localhost:8000/predict)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Application deployed successfully! HTTP Status Code: $RESPONSE"
            echo "Verifying model response..."
            curl -X POST -H "Content-Type: application/json" \
              -d '{"features": [13.2, 2.77, 2.51, 24.5, 86.0, 1.45, 1.25, 0.5, 1.7, 6.5, 1.05, 3.33, 820.0]}' \
              http://localhost:8000/predict
          else
            echo "Deployment failed! HTTP Status Code: $RESPONSE"
            exit 1
          fi

      - name: Stop and Remove Docker Container
        if: always()
        run: |
          docker stop mlops-app
          docker rm mlops-app
