name: CI/CD Pipeline with Codespaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  lint:
#    name: Lint Code
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#
#      - name: Install Dependencies
#        run: |
#          pip install flake8
#          pip install -r requirements.txt
#
#      - name: Run Linter
#        run: flake8 . || true
#
#  test:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#    needs: lint
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#
#      - name: Install Dependencies
#        run: |
#          pip install -r requirements.txt
#
#      - name: Run Unit Tests
#        working-directory: ./
#        run: python -m unittest discover -s src/test/unit_test -p "*.py"

  deploy-to-codespaces:
    name: Deploy to Codespaces
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.DEPLOY }}
        run: |
          echo "${{ secrets.DEPLOY }}" | gh auth login --with-token
          gh auth refresh -h github.com -s codespace

      - name: List Available Codespaces
        run: gh codespace list

      - name: Deploy Application to Codespace
        run: |
          gh codespace ssh -c mlops-deployment -C "
          cd /workspaces/ml-ops-grp39-assignment-1 &&
          docker build -t mlops-app:latest . &&
          docker run -d -p 5000:5000 mlops-app:latest
          "

      - name: Manual Port Forwarding Instructions
        run: |
          echo "Go to the Codespaces Ports tab and make port 5000 Public."
